### ISSUE TITLE
能否更新 CUDA docset 版本

### ISSUE THREAD

**Issue by moeakwak** [blahgeek/dashdoc-cuda#2]
Hi, 注意到您贡献的 CUDA docset 许久未更新版本: https://github.com/Kapeli/Dash-User-Contributions/tree/master/docsets/CUDA/versions
请问是否方便提交 PR 以更新文档？
如无后续维护文档的计划也请告知，感谢！

**Comment by blahgeek** [comment]
hello, 我很久没有用Dash了（因为开发环境变到了linux），所以可能短期不会更新。欢迎帮忙提交PR。谢谢！

**Comment by blahgeek** [comment]
https://github.com/blahgeek/dashdoc-cuda/pull/4
